server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/subscribers?currentSchema=subscribers
    username: postgres
    password: masha

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

log:
  folder: log

rest:
  connectTimeout: -1
  readTimeout: -1
